### ISSUE TITLE
Provided scope causing ClassNotFoundException

### ISSUE THREAD

**Issue by Magador** [seedstack/jcache-addon#5]
In the documentation:

> JCache specification jar dependency is required as well:
> ```
> <dependency>
>     <groupId>javax.cache</groupId>
>     <artifactId>cache-api</artifactId>
>     <version>1.0.0</version>
>     <scope>provided</scope>
> </dependency>
>```

When setting the required JCache specification jar dependency, the `<scope>` should not be `provided` as shown in the docs because not all servers provide this lib.

**Comment by adrienlauer** [comment]
Sure i'm just rewriting this doc and will fix this.
